### ISSUE TITLE
implement wikibase-term IMAGE-LIVE attribute natively in WikipediaBase

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#100]
The `wikibase-term IMAGE-LIVE` attribute is implemented as an Omnibase script purely for hysterical raisins.  It no longer makes a lick of sense to keep this functionality in Omnibase.  We should move it to WikiBase, but note that the Omnibase script allows a file size specification, and we'd have to figure out how to represent that in WikiBase.  Maybe allow additional keyword-value pairs in attribute descriptors (that is, in addition to `:code` and `:rendered`)?  Like this?

    (get "wikibase-term" "Tiger" (:code "IMAGE-LIVE" :size 50))

**Comment by alvaromorales** [comment]
IMAGE-LIVE should return a list of one item containing the first image in the IMAGE-DATA list, optionally resized if `:size` is specified.

E.g.: `(get "wikibase-term" "Bill Clinton" (:code "IMAGE-LIVE" :size 350))` should return the image in Bill Clinton's infobox, resized to 350px.

Wikipedia has a really neat way of resizing images on the server.

Original image URL: https://upload.wikimedia.org/wikipedia/commons/4/49/44_Bill_Clinton_3x4.jpg

URL of same image resized to 350px: https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/44_Bill_Clinton_3x4.jpg/350px-44_Bill_Clinton_3x4.jpg

URL of same image resized to 10px: https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/44_Bill_Clinton_3x4.jpg/10px-44_Bill_Clinton_3x4.jpg

If a size is specified, IMAGE-LIVE needs to make these changes to the image URL:

https://upload.wikimedia.org/wikipedia/commons **/thumb** /4/49/44_Bill_Clinton_3x4.jpg **/SIZEpx-44_Bill_Clinton_3x4.jpg**

Note that an image URL might already contain '/thumb', in which case we only need to append to the end of the URL.

Also, I think this **only** works for images in the Wikipedia Commons ('/commons/' in URL). Here's an example of an image that's _not_ in the commons: https://upload.wikimedia.org/wikipedia/en/8/89/Hanmerst.jpg. I can't get resizing to work. We should investigate this further.

**Comment by sherryy** [comment]
I invested on resizing images from Wikipedia Commons. It turns out that all images can all be resized using the techniques mentioned above, regardless weather they are from Wikipedia Commons or not. The Hanmerst image after resize:

https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Hanmerst.jpg/120px-Hanmerst.jpg

thumb should occur after "/en/" and before "/8/89"
