### ISSUE TITLE
IMAGE-DATA wrongly returning no value in some cases

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#110]
Why no image data?  There are lots images in the https://en.wikipedia.org/wiki/Flower article.

    (get "wikibase-term" "Flower" (:CODE "IMAGE-DATA"))
    ((:error attribute-value-not-found :message "Unknown"))

**Comment by alvaromorales** [comment]
> IMAGE-DATA, wikibase-term
> Returns a list of URLs for images in the article content (excludes images that are in the page but outside of the article content, e.g. Wikipedia's logo). If there are no images, should return an empty list. The "best" image should be the first URL in the list; if there is a picture at the top of the infobox, this is considered to be the best image, or otherwise the first image that appears anywhere in the article. If there is no caption, the caption value should be omitted, e.g., ((0 "Harimau_Harimau_cover.jpg")) rather than ((0 "Harimau_Harimau_cover.jpg" "")).

IMAGE-DATA is implemented in `TermResolver`: https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/resolvers/term.py#L48

**Comment by sfelshin** [comment]
Also note:

    (get "wikibase-term" "France" (:code "IMAGE-DATA"))
    ((:error AttributeError :message "'NoneType' object has no attribute 'replace'"))

**Comment by sfelshin** [comment]
For test cases, please make sure there are at least the following tests:

* single image in infobox
* multiple images in infobox -- first is "best"
* single image in article body
* multiple images in article body -- first is "best"
* images in both infobox and article body -- first in infobox is "best"
* captions are correctly returned in all the above cases
* images and logos in Wikipedia banner and sidebar are never returned, e.g., Wikipedia logo
* Wikipedia logo _is_ returned when it appears in the article content (like, an article about Wikipedia itself)

**Comment by alvaromorales** [comment]
Perhaps we should clean up IMAGE-DATA's output format. Instead of:

```lisp
((0 "Harimau_Harimau_cover.jpg" "Caption") (1 "Other_image.jpg"))
```

Can we return an _ordered_ list of plists? (In Python, this translates to a list of dictionaries)

```lisp
((:file "Harimau_Harimau_cover.jpg" :caption "Caption") (:file "Other_image.jpg"))
```

@sfelshin, what do you think?

**Comment by sherryy** [comment]
Is that the case that we don't need the number index? I have been doing it the old way but glad to change it if necessary.

**Comment by sfelshin** [comment]
WFM.
