### ISSUE TITLE
bad(?) synonym "directed" -- maybe many more like it

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#112]
Why do so many articles have `directed` as a synonym?  When I go to the article for `Sports director` and chase the "What links here" link, I don't find anything about "directed". Ditto "Left 4 Dead".
 
    START> (omnibase-get-symbols "directed" :class "wikibase-term")
    ((WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Sports director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Left 4 Dead" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Non-executive director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "HMS Director (1784)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Artistic director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Music video director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Music director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Funeral director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Film director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Fibre Channel switch" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Executive director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director telephone system" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director string" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director (military)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director-general" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director (colonial)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director (business)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director (band)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Director (album)" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Cruise director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Creative director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Courage Brewery" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Chief financial officer" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Chief executive officer" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Adobe Director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Aaron Director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Tournament director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "The Director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Theatre director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Television director" :PRIORITY 0)
     (WIKIBASE-TERM "directed" :SPAN (0 8) :NAME "Technical director" :PRIORITY 0))

Bogus synonyms slow START down by making it waste time temporarily defining them as words and then undefining them (which requires calls to WikipediaBase's `get-classes`, among other work), so it's pretty important to eliminate bogus synonyms.

**Comment by sfelshin** [comment]
Note that `directing` is a synonym of the same of articles:

    START> (omnibase-get-symbols "directing" :class "wikibase-term")
    ((WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Sports director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Left 4 Dead" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Non-executive director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "HMS Director (1784)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Artistic director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Music video director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Music director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Funeral director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Film director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Fibre Channel switch" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Executive director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director telephone system" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director string" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director (military)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director-general" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director (colonial)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director (business)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director (band)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Director (album)" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Cruise director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Creative director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Courage Brewery" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Chief financial officer" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Chief executive officer" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Adobe Director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Aaron Director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Tournament director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "The Director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Theatre director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Television director" :PRIORITY 0)
     (WIKIBASE-TERM "directing" :SPAN (0 9) :NAME "Technical director" :PRIORITY 0))

But not `directs` or `direct`:

    START> (omnibase-get-symbols "directs" :class "wikibase-term")
    NIL
    
    START> (omnibase-get-symbols "direct" :class "wikibase-term")
    ((WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Sprint Corporation" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Mars Direct" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "AOL Instant Messenger" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Random access" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "DirectX" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct (Vangelis album)" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct (Tower of Power album)" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct sum of modules" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct memory access" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct limit" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct examination" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct (EP)" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Directed set" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "DIRECT" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct current" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct Connect (protocol)" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct-access trading" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct Access Test Unit" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct-access storage device" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "DirectAccess" :PRIORITY 0)
     (WIKIBASE-TERM "direct" :SPAN (0 6) :NAME "Direct Access Archive" :PRIORITY 0))

Here's the problem:

* `Directed` (https://en.wikipedia.org/w/index.php?title=Directed&redirect=no), and also `Directing`, `Directors`, `Directer`, etc., redirect to the Wikipedia disambiguation page for `Director` (https://en.wikipedia.org/wiki/Director).

* `Director` (https://en.wikipedia.org/wiki/Director) disambiguates in various reasonable ways, e.g., to "Film director" and "Sports director".

* `Director` (https://en.wikipedia.org/wiki/Director) also disambiguates in some unreasonable ways, e.g., `<li>Director, the spatial and temporal average of the orientation of the long molecular axis within a small volume element of <a href="/wiki/Liquid_crystal#Director" title="Liquid crystal">liquid crystal</a></li>` and `<li>The Director, a complex artificial intelligence system used in the video game <i><a href="/wiki/Left_4_Dead" title="Left 4 Dead">Left 4 Dead</a></i></li>`. See https://github.com/infolab-csail/WikipediaBase/issues/101 re `Flower` as a poor synonym of `Bambi` for how to detect and eliminate this kind of unreasonable synonym.

* Even if we addressed the Flower / Bambi problem, we would still calculate that `Directed`, `Directing`, `Directors`, `Directer`, etc., are synonyms of `Sports director`, `Television director`, `Adobe Director`, `Director (band)`, etc. It's not so bad if `Directors` and `Directer` are synonyms of these symbols, but it's pretty bad if `Directed` and `Directing`, especially for `Adobe Director` and `Director (band)` that aren't even kinds of directors. Could WikiThingsDB help with this?

* Can we use part-of-speech information to eliminate undesirable synonyms?  E.g., "directed" is a verb participle, not a noun.  It's okay for Wikipedia to make "Directed" redirect to "Director" because Wikipedia does object lookup.  START does natural language question answering, so the phrase expressing the object has to fit into a sentence. It's ungrammatical to ask "Tell me about directed." We could prevent synonymy when the two items' parts of speech differ. There are two problems with this:

   * It _is_ grammatical to ask about any part of speech if you use quotation marks, e.g., "Tell me about 'directed'."

   * "Directing" _can_ be a noun -- a gerund.

For now, how about if we eliminate all the types of synonyms I've complained about here, but consider adding them back in someday if we can give them subnormal priority values?  See https://github.com/infolab-csail/WikipediaBase/issues/101 about distinguishing more priority values.

Oh, and by the way, here's another test case: `direct` is a synonym of `Sprint Corporation`, and ideally it shouldn't be. Sprint has a service called `Direct connect`, which redirects to Sprint, as you can see at https://en.wikipedia.org/wiki/Special:WhatLinksHere/Direct_connect. There's a disambiguation page for `Direct connect`, and `Direct` links to it. Can we come up with a way to eliminate this synonymy without eliminating valid synonyms, or are we just stuck with it?

**Comment by alvaromorales** [comment]
Using a POS tagger could help us get rid of bad synonyms (I'm not so sure about WikithingsDB). However, I'm worried it would be prohibitively expensive. Generating synonyms already takes 40+ hours on a beefy machine like nauru. I'd like to start by exploring solutions that don't use an external library.

We didn't see this bug in Ruby-Wikibase because we didn't recursively following disambiguation pages. We should be much stricter in how we determine that something is a synonym.

Some preliminary ideas:

* Let `num_hops` be the number of links you have to follow until you find a symbol. Limit `num_hops` to 1 or 2.
 
  * Good: `A -> B -> C (symbol)`. Make `B` and `A` synonyms of `C`.
  * Bad: `A -> B -> C -> D -> E (symbol)`. Don't create any synonyms from this chain.

* Don't follow links with local anchors. It's unlikely that these are valid synonyms of the article title.

  * Good redirect: `https://en.wikipedia.org/wiki/Sprint_Corporation`
  * Bad redirect: `https://en.wikipedia.org/wiki/Sprint_Corporation#Sprint_Direct_Connect`

* Don't resolve redirects that point to disambiguation pages.

  * Good: `A (redirect) -> C (symbol)`. Make `A` a synonym of `C`.
  * Bad: `A (redirect) -> B (dis) --> C (symbol)`

* Add all verbs (+ conjugations?) in START's lexicon to `wikibase-term-exclude-synonyms`

**Comment by sfelshin** [comment]
I like Alvaro's ideas. Let's do some investigation of what proportion of symbol-synonym pairs they eliminate, and let's spot-check a few of the eliminated pairs to see if we're happy with removing them. I don't think we should add _all_ verb forms in START's lexicon to `wikibase-term-exclude-synonyms` because too many verb forms are also nouns and other parts of speech. Perhaps we could exclude all verb forms that can _only_ be verbs in START. Or perhaps do exclude multi-POS verb forms, but only if we can somehow determine that their verb sense is more common than their other senses (not sure how we'd do that).

In the long run, we might want to do something even more complex, taking into account what people are likely to ask about. Would anyone ask "Tell me about 'directs'?" and want information about sports directors? That seems unlikely. But perhaps someone might ask "Who developed Director?" or "What kind of licensing does Director have?". Here are some ideas for more complex ways to choose synonyms: Only add a synonym that can be a verb (according to START) if the Wikipedia article is about a proper noun rather than a common noun -- or perhaps vice versa. Or, only if the verb form is the infinitive or present participle (not third person singular present tense, past tense, or past participle). Or, only if the article is for a proper noun. Or, only if the synonym is a single hop away (`A -> B`), or maybe even zero hops (that is, only if the synonym is derived from the article title itself). Or, only if the article has an infobox. Or...

**Comment by sfelshin** [comment]
Another example of an undesirable synonym: "THE" is generated as a synonym of "Texas Hold'Em".  See https://en.wikipedia.org/wiki/Special:WhatLinksHere/Texas_hold_'em. Omnibase's exclude-synonyms files (https://groups.csail.mit.edu/infolab/internal/srcdocs/omnibase/db-editors-guide.html#exclude-syns) only allow us to exclude synonyms according to the synonym; that is, for the given synonym, every symbol-synonym pair gets excluded. Compare Omnibase's include-synonyms files wherein we include specific symbol-synonym pairs. If we can't find a good way to exclude `THE -> Texas Hold'Em` according to hops or one of the other means noted above, maybe we need to be able to exclude specific symbol-synonym pairs, whether in Omnibase or when WikipediaBase generates the pairs. It would be nice if we could keep `The` as a synonym for the definite article, the musical group `The The` (see https://groups.csail.mit.edu/infolab/internal/srcdocs/omnibase/db-editors-guide.html#bad-syns regarding removing leading articles from synonyms), the surname `The`, and other articles that don't have better names. But for `Texas Hold'Em` and `T.H.E.`, it wouldn't be so bad to force the user to use the more explicitly correct and complete name.

**Comment by fakedrake** [comment]
I am probably not the best person here to comment on this, but I thought tagging POS using pre-trained models should be fairly cheap. Especially given that the context in titles is very limited [1], it I wouldn't expect it to be more expensive than a bunch of regular expression matches.

That said, albeit it being a much more exciting technique, you have come up with so many examples where POS would lead to the wrong direction. Pruning the redirect/disambiguation tree, like @alvaromorales suggests, is a much lower hanging fruit (no pun intended).

[1] Unless we want to look at the first sentence which I would guess will have many strange edge cases.
