### ISSUE TITLE
Synonym generation speedup

### ISSUE THREAD

**Issue by fakedrake** [infolab-csail/WikipediaBase#114]
I just read in issue #112 @alvaromorales said

> Generating synonyms already takes 40+ hours on a beefy machine like nauru.

It was my understanding that the (useful) data to be crunched for this operation is at the order of 10s of GB at most. Performance at compile time is not really a pressing issue but if we are to use more sophisticated methods of getting synonyms (like suggested in #112) we should at least give it a little bit of thought. Looking at the code generating the synonyms I would make the following suggestions:

- We go over [each article](https://github.com/infolab-csail/WikipediaBase/blob/master/scripts/generate_symbols_and_synonyms.py#L94) in the database and then [query again](https://github.com/infolab-csail/WikipediaBase/blob/master/scripts/generate_symbols_and_synonyms.py#L94) for the markup. We could save a few disk accesses by using the markup we got the first time around. I didn't look too much into what optimizations we get from the various libraries we use but from a quick look I would say not many.
- Given the size of the (zipped) *all titles* from the dumps, we might afford to build the entire redirect graph in-memory and then traverse it to generate the symbol trails. This could avoid duplicate lookups and allow the database to make better use use it's cache.
- We check each article if they are [redirect or disambiguation](https://github.com/infolab-csail/WikipediaBase/blob/master/scripts/generate_symbols_and_synonyms.py#L61L62) pages. We could instead use the [dumps](http://dumps.wikimedia.org/enwiki/20151201/) to get:

  - A list of all the *redirects*
  - A list of the disambiguation pages looking up the `disambiguation_pages` category from the *category membership* dump.
   - Pages ending with *"(disambiguation)"* from the dump of *all titles*.

I didn't actually implement any of the above so this is [mostly](https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/WikipediaBase#Get_synonyms_from_redirects) speculative suggestions. What do you think?

**Comment by alvaromorales** [comment]
Thanks for the suggestions. Querying again for markup is an oversight, I've removed it in #121.

Given that Everything in Wikipedia is Hard, we actually do need to look at markup to correctly identify disambiguation pages -- many disambiguation pages don't have the category or (disambiguation) in title.

With the new updates to the generation procedure, the script takes 40 hours. I'm fine with this, optimizing it to 20 hours wouldn't make much of a difference. I don't think using a POS tagger is necessary anymore. We might need to revisit performance tuning in the future.
