### ISSUE TITLE
KnowledgeBase potential recursion

### ISSUE THREAD

**Issue by fakedrake** [infolab-csail/WikipediaBase#14]
Since knowledgebase's services are available to other knowledgebase services there may potentially be a recursion.  Eg.

	get_classes(a) : ... classify_as_person(a) ...
	classify_as_person(a) : ... if knowledgebase.get_attributes(a, birth-date): append_class() ...
	get(a, attr) : ... get_plant_related(a, attr)
	get_plant_related(a, attr) : if 'xxx' in get_classes(a) ...

so the `get_plant_related` attribute resolver probably doesn't know about the person related wirings, but it will cause a nasty recursion.

If this kind of issue comes up, disable each subfacility while it is being called.

**Comment by fakedrake** [comment]
This will be a major problem when extending wikibase on separate modules. Use python environments to modify the behaviour of util.get-classes to change the scope of knowledgebase functions

**Comment by alvaromorales** [comment]
Circular dependencies have been mostly fixed. We don't have plans to extend KnowledgeBase from a separate module.
