### ISSUE TITLE
Deprecate typed lists over plists

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#143]
Per #120, I think it's a good idea to push the lispify logic down to the frontend modules, not the knowledge base or resolvers. This gets complicated because we have to return lists with typecodes.

Python doesn't natively support lists with typecodes. We could wrap the native list with a custom class, but I'd rather look for a simpler solution.

The lispify module does a great job at translating dictionaries to plists. What if we deprecate typed lists over plists? In the external API, this would only involve one change.

Instead of returning:

```lisp
(get "wikibase-term" "Black Sea" (:code "COORDINATES"))
((:coordinates 44 35))
```

we would return:

```lisp
((:coordinates (44 35)))
```

@sfelshin would this be okay?

**Comment by sfelshin** [comment]
Works for me.  I can change START to handle either format to avoid having a flag day.

**Comment by alvaromorales** [comment]
Great!

Every resolver should return a list of dictionaries. The call to lispify should be made in frontend.py.
