### ISSUE TITLE
New output format for IMAGE-DATA (v.1.1.0)

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#162]
START needs to be updated to use the new output format of `IMAGE-DATA`.

Old format:

```lisp
(get "wikibase-term" "Foo" (:code "IMAGE-DATA"))

((0 "filename" "some caption") (1 "filename2"))
```

New format:
```lisp
((:file "filename.jpg" :caption "some caption") (:file "filename2"))
```

**Comment by sfelshin** [comment]
@alvaromorales and @chsamlee, what's the status of options in `get` commands?  I experienced this just now:

```
$ telnet kiribati 8023
(get "wikipedia-sea" "Black Sea" (:code "AREA") ())
((:error IndexError :message "list index out of range"))
```

@sherryy, what's the status of `IMAGE-LIVE`?  I experienced this just now:

```
$ telnet kiribati 8023
(get "wikibase-term" "Black Sea" (:code "IMAGE-DATA"))
((:file "Black_Sea_map.png") (:caption "Georgia]]" :file "Black_Sea_Coast_of_Batumi%2C_Georgia_%28Europe%29.jpg") ...)
$ telnet kiribati 8023
(get "wikibase-term" "Black_Sea_map.png" (:code "IMAGE-LIVE"))
((:error attribute-value-not-found :message "Unknown"))
```

**Comment by chsamlee** [comment]
The `get` options enhancement is still in PR process, but the empty tuple issue needs to be fixed. As for `IMAGE-LIVE`, I think the changes have been merged into master after the ver. 1.1.0 release.

**Comment by sfelshin** [comment]
> START needs to be updated to use the new output format of IMAGE-DATA.

@alvaromorales, that's what I was working on when I ran into the above-cited issues. @chsamlee, thanks for the update. For now I've patched my updates to START by removing any options before sending `get` commands to WikipediaBase, but `IMAGE-LIVE` is still a problem.

**Comment by alvaromorales** [comment]
`IMAGE-LIVE` is not part of the 1.1.0 release (see [changelog](https://github.com/infolab-csail/WikipediaBase/blob/master/CHANGELOG.md#110-2016-01-26)).

The empty options issue is a bug, I've opened #172.

**Comment by sfelshin** [comment]
This is complete in a START branch revision but not yet installed. See however https://github.com/infolab-csail/WikipediaBase/issues/179.
