### ISSUE TITLE
New output format for COORDINATES (v.1.1.0)

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#163]
START needs to be updated to use the new output format of `COORDINATES`.

Old format:

```lisp
(get "wikibase-term" "Foo" (:code "COORDINATES"))

((:coordinates 44 35))
```

New format:
```lisp
((:coordinates (44 35)))
```

**Comment by sfelshin** [comment]
I've committed the necessary changes in START, although as far as I can tell all articles suffer from the "works the first time" problem for coordinates (https://github.com/infolab-csail/WikipediaBase/issues/150), so testing is annoying.
