### ISSUE TITLE
Empty options plist causes IndexError

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#172]
The `get` API is: `(get class symbol attribute-plist options-plist)`.

`options-plist` is an _optional_ argument, so the caller can specify no options or pass an empty list.

Passing an empty plist of options causes an error:

```lisp
(get "wikipedia-sea" "Black Sea" (:code "AREA") ())
((:error IndexError :message "list index out of range"))
```

**Comment by sfelshin** [comment]
Oops, pasted the wrong URL and falsely closed this issue.  Reopened.

**Comment by sfelshin** [comment]
Now re-closing to its former closed state.
