### ISSUE TITLE
No ability to return empty lists

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#204]
In #203, @chsamlee brought up an interesting limitation (feature?) of the WikipediaBase API (slightly edited):

> There is no way for a resolver to return an **empty list** at this moment (e.g. `IMAGE-DATA` won't return an empty list for an article with no images). Empty lists are treated as "no result". We continue to look for an answer from other resolvers, eventually ending up with a useless `attribute-value-not-found` error.

@sfelshin, is this the expected behavior? Is there a situation where we would prefer an empty list over an error?

**Comment by sfelshin** [comment]
START expects `IMAGE-DATA` to return an empty list if WikiBase successfully determines that there are no images.  (If there was a problem in searching the page for images, like bad HTML, that could result in an error.)  START expected this behavior back in Ruby WikiBase.  If it's a problem, we can change the handshake to expect an error instead.  What do you prefer?

**Comment by chsamlee** [comment]
It should not be hard to fix this problem, and the ability to return empty list seems to be useful in general.
