### ISSUE TITLE
Coordinates included in output of SHORT-ARTICLE

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#206]
Why are coordinates included in the output of `(get "wikibase-term" "Ascot Gold Cup" (:code "SHORT-ARTICLE"))`?

> ===> Tell me about Ascot Gold Cup

> Ascot Gold Cup

> Coordinates: 51°24′43.8″N 0°40′45.3″W﻿ / ﻿51.412167°N 0.679250°W
The Gold Cup is a Group 1 flat horse race in Great Britain open to horses aged four years or older. It is run at Ascot over a distance of 2 miles and 4 furlongs (4,023 metres), and it is scheduled to take place each year in June.

> It is Britain's most prestigious event for "stayers" – horses which specialise in racing over long distances. It is traditionally held on day three of the Royal Ascot meeting, which is known colloquially (but not officially) as Ladies' Day. Contrary to popular belief the actual title of the race does not include the word "Ascot". In 2016 it will be run as "the Gold Cup in Honour of The Queen's 90th Birthday".[1]

**Comment by chsamlee** [comment]
The problem is that Wikipedia has no standard on where to insert the coordinates HTML. When the coordinates span is inserted in the beginning of article, Article.first_paragraph includes it in the result. Another example of this is United States.
