### ISSUE TITLE
Bogus value for wikipedia-writer (:code "SIGNATURE")

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#213]
It doesn't contain a signature, it doesn't contain any content that can be rendered visibly, and it contains illegal HTML. (Other than that, Mrs. Lincoln, how do you like the attribute value?)
```
$ telnet kiribati 8023
(get "wikipedia-writer" "Alexander Pushkin" (:CODE "SIGNATURE"))
((:html "<i>"))
$ telnet kiribati 8023
(get "wikipedia-writer" "Alexander Pushkin" (:rendered "Signature"))
((:html "<i>"))
```

For extra jollies, when I view the page source I don't see an `<i>` tag anywhere in or around the signature.

**Comment by chsamlee** [comment]
This bug is fixed in #209. With the current master, both queries return` ((:html "Pushkin Signature.svg"))'. Whether we should get the actual image for `:rendered` is a different story though.
