### ISSUE TITLE
Noam Chomsky isn't a wikibase-person

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#216]
```
$ telnet kiribati 8023
(get-classes "Noam Chomsky")
("wikibase-term" "wikibase-sections" "wikipedia-philosopher")
```
This means START can't answer "How old is Noam Chomsky"—it can't match START's native annotation for "how old is _any-wikibase-person_".

**Comment by chsamlee** [comment]
If the wikibase-person classifier finds "lists of " in a category, then the classifier treats the term as a non-person. Unfortunately, Chomsky has a category named "Members of the Democratic Socia**lists of** America."
