### ISSUE TITLE
Truecase attribute names

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#218]
Currently, all attribute names from infobox templates get uppercased.  (Rendered attribute names retain their true case.) E.g., `(:code  "MAINSPAN" :rendered "Longest span")`.  It is an artifact of history that we convert these `:code` attribute names to upper case:  WikipediaBase does it to be like Omnibase, but in Omnibase, attributes aren't connected to source code, so any case is accurate (and upper case was chosen for convenience in START).  However, forced upper case is inaccurate in WikipediaBase.

Implications and issues:
   - I assume it would simplify the WikipediaBase code base (slightly) to retain truecasing.
   - START converts external attributes (from Omnibase and WikipediaBase), which it implements as strings, to its internal representation of "fields", which it implements as symbols.  In Lisp, by default, all symbol names are stored in upper case.  Lower case and mixed case symbols can be represented, but are less convenient for humans to type and read.  We would have to reformat all WikipediaBase attributes that have been typed literally in START.  E.g., in a schema function calls, replace `(show-wikipedia-referent-literal 'wikipedia-aircraft-type ... '(manufacturer first-flight number-built)` with `(show-wikipedia-referent-literal 'wikipedia-aircraft-type ... '(|manufacturer| |first-flight| |number-built|)`.  And similarly for START-native definitions of Wikipedia classes and any other code.  (To make life easier, we should first remove the many unnecessary START-native definitions of Wikipedia classes and attributes that have no START-native schemata and are handled by AOPV or not at all.)
   - START's AOPV code performs fuzzy-matching of Omnibase and WikipediaBase attribute names to START vocabulary.  START's vocabulary is stored as Lisp symbols using the default upper case (\*whimper\*), so `query-field-matches-field-p` would have to perform its fuzzy matching ignoring case for WikipediaBase attributes, which would be a little slower (test with `string-equal` instead of `string=`) and/or cons a little more (convert attributes to upper case before matching, preferably by stack-consing them).  Would the loss in efficiency be big enough to matter?

Before proceeding with this, we would have to discuss whether we really want it, given the required changes in START.

**Comment by sfelshin** [comment]
Note that `wikibase-*` attributes can stay in upper case since they don't map to attributes in Wikipedia.  This will substantially reduce the number of string replacements needed in START code, since most START-native schemata for Wikipedia are for `wikibase-*` attributes.

On the one hand, upper case is ANNOYING SHOUTING, but on the other hand, it's doesn't seem so much like shouting in code, and leaving `wikibase-*` attributes in upper case would help to distinguish them from Wikipedia infobox attributes.

**Comment by alvaromorales** [comment]
The WikipediaBase API is insensitive to attribute case. Internally, code attribute names are all lowercased. This means that the following are equivalent API calls:

```
(get "wikipedia-president" "Bill Clinton" (:code "PARENTS"))
(get "wikipedia-president" "Bill Clinton" (:code "parents"))
(get "wikipedia-president" "Bill Clinton" (:code "Parents"))
```

I think this is a feature of WikipediaBase that helps reduce the complexity of ad-hoc infobox templates.

From what I've been able to read about Wikipedia, code attributes don't have a "true" case. Rather, they are inconsistently named by editors that don't follow guidelines.

>  Parameters are case sensitive. **Nearly all infoboxes use lowercase parameter labels**.
-- https://en.wikipedia.org/wiki/Help:Infobox

I would suggest that having case-insensitive code attributes in WikipediaBase is a nice feature (if so, we should mark this issue as `wontfix` and close it).

On the START side, it looks like a lot of changes would be necessary if we were to truecase attribute names. I don't see a clear benefit of doing so. WikipediaBase's core is wired to lowercase attributes. Many upstream functions thus assume that attribute names are lowercased. It would take quite a bit of work to trace through every function and determine if the change is safe.

Besides, if we really wanted to stay accurate to Wikipedia attribute names, we would not replace underscores with dashes (`ATTRIBUTE-NAME` --> `attribute_name`).

[I meant to add this comment last week, it was sitting here as a draft].

**Comment by sfelshin** [comment]
I concur that this isn't worth implementing.  I'm glad to have this discussion stored in GitHub, though.  Thanks for your comments. 😄
