### ISSUE TITLE
Calculate gender at compile time and store in backend

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#237]
(cc @boriskatz) The `wikibase-person GENDER` script calculates gender based on counts of gendered pronouns in the article text.  Would it be reasonable to calculate this information at compile time and store it in the backend?  I imagine the answer depends in part on whether we would process the source or rendered page. 

Priority is medium to high on figuring out how practical this idea is.  Priority on actually implementing this idea depends on the preliminary answer.  If it would take too much longer to rebuild the backend (cc @michaelsilver), I don't think we would proceed at all.

**Comment by chsamlee** [comment]
On average it takes 30 milliseconds to compute the gender of an article. Wikipedia has roughly 5.2 million articles, which means it will take around 43 hours to compute the gender for all articles. Classifying whether an article is a person takes roughly the same time as computing the gender, so the number should be a good approximation for lower bound (we still need to deal with redirects and data storage).

Currently the backend takes 5 days to rebuild according to @michaelsilver, and this change will increase the rebuild time to one week. Calculating this information at compile time doesn't increase Wikipediabase's performance (as most of the time is spent on fetching the markup).

**Comment by michaelsilver** [comment]
Doesn't seem like it's worth it for multiple reasons, as mentioned by @chsamlee in his comment. In addition, right now the backend generation script is resource intensive and the two times I've run it I've gotten a `(core dumped)`, which is a linux kernel fluke, so I'd rather not add more steps to the backend generation script at the moment. Maybe we could revisit this in the future.

(If I get the `(core dumped)` the next time I generate the backend, I will open an issue about it.)
