### ISSUE TITLE
Document and add ability to flush the Redis cache when restoring the backend

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#238]
(I'm adding this issue in this repository because it serves as a larger point about WikipediaBase, although it references improving a script in `github:infolab-core`.)

@cheahuychou did a `wikipediabase.article.get_article().markup_source()` on futuna and got an ancient version of the article's markup, so she asked me to update the backend. But after updating the backend from an ancient version to the most recent one using `restore-wikipediabase.sh` (and even deleting the database and trying a second time), we were still getting the same old markup.

Turns out what was happening was the Redis cache was [kicking in](https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/fetcher.py#L108) and returning the old cached article -- even though the backend was updated. This is deeply disturbing because when we update the backend on full START stacks for testing and/or production, we expect the answers we are getting to reflect the newest backend. But unless we flush the cache, we will continue to get old answers.

To properly address this, we need to:
- [x] Add documentation warning people about the Redis cache. This should probably go in the updated instructions on the internal infolab wiki (see https://github.com/infolab-csail/WikipediaBase/issues/104) about how to backup/restore the backend.
- [x] The last step in `github:infolab-core/bash_src/restore-wikipediabase.sh` should be a y/n question asking the user whether to clear the cache, automatically clearing it via `$ redis-cli flushall`

**Comment by chsamlee** [comment]
Because redis may be used by multiple applications, we should only flush keys that are set by Wikipediabase. This involves changing `fetcher.py` and `renderer.py` to add a `wikipediabase-` prefix when getting/setting keys, and find the command that only flushes keys with specific prefix.

**Comment by michaelsilver** [comment]
@chsamlee I like that idea; it seems like the most robust approach. Could you look into how complicated this is, and if it's not too hard, go ahead and implement the unique prefix? Otherwise, we can leave it for a later enhancement when we do get multiple systems using Redis.

**Comment by sfelshin** [comment]
> The last step in github:infolab-core/bash_src/restore-wikipediabase.sh should be a y/n question asking the user whether to clear the cache

A couple of suggestions:
   - Rather than making this the last step, ask the question up front ("after updating the backend, should I clear the cache?", only with better wording) so that the user can execute the job, walk away, and have the job complete without further interaction.
   - Add a command line argument, and if the argument is explicitly supplied, then the user won't get asked the question.
