### ISSUE TITLE
Attributes in meta infoboxes shouldn't map to the empty string

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#24]
Some attributes map to an empty string (`u''`) when fetched using:

```python
from wikipediabase.infobox import get_meta_infobox
get_meta_infobox('<TEMPLATE_NAME>').attributes
```

Any idea why this is happening?

Below is a list of tuples in the form `(attribute, [list of infoboxes for which this happens])` for all attributes that map to the empty string:
```
(u'DST_note', [u'Template:Infobox country'])
(u'nebty_hiero', [u'Template:Infobox pharaoh'])
(u'junction', [u'Template:Infobox road'])
(u'female_weight', [u'Template:Infobox animal breed'])
(u'mottotranslated', [u'Template:Infobox law enforcement agency'])
(u'life_span', [u'Template:Infobox former subdivision'])
(u'coach_year', [u'Template:Infobox college inline hockey team', u'Template:Infobox college ice hockey team'])
(u'year_end', [u'Template:Infobox former country'])
(u'motto_translated', [u'Template:Infobox law enforcement agency'])
(u'female_height', [u'Template:Infobox animal breed'])
(u'birth_place', [u'Template:Infobox family'])
(u'femaleheight', [u'Template:Infobox goat breed', u'Template:Infobox donkey', u'Template:Infobox pig breed', u'Template:Infobox water buffalo breed', u'Template:Infobox cattle breed', u'Template:Infobox sheep breed'])
(u'coach_ties', [u'Template:Infobox college inline hockey team', u'Template:Infobox college ice hockey team'])
(u'golden_hiero', [u'Template:Infobox pharaoh'])
(u'coach_losses', [u'Template:Infobox college inline hockey team', u'Template:Infobox college ice hockey team'])
(u'year_start', [u'Template:Infobox former country'])
(u'area_note', [u'Template:Infobox settlement'])
(u'population_note', [u'Template:Infobox settlement'])
(u'femaleweight', [u'Template:Infobox goat breed', u'Template:Infobox poultry breed', u'Template:Infobox donkey', u'Template:Infobox pig breed', u'Template:Infobox water buffalo breed', u'Template:Infobox cattle breed', u'Template:Infobox sheep breed'])
(u'coach_wins', [u'Template:Infobox college inline hockey team', u'Template:Infobox college ice hockey team'])
```

**Comment by fakedrake** [comment]
I am not sure what is going on, could you describe the steps for reproducing this in a bit more detail?

**Comment by michaelsilver** [comment]
I created a tool called [Attribute Analyzer](https://github.com/michaelsilver/Attribute-Analyzer) to analyze the unrendered ==> rendered attribute relationships by representing each rendered or unrendered attribute as a node and joining nodes together by directed edges to form a graph showing all the attribute mappings. In other words, from WikipediaBase I get the mappings A --> B and C --> B, and I represent this as:
```
A --> B
      ^
      |
      C
```
To answer your question, I found all attributes mapping to the empty string (`''`) simply by listing all nodes that are joined to the `''` node (and I also extracted their infobox while I was at it). If you want to reproduce this, clone [Attribute Analyzer](https://github.com/michaelsilver/Attribute-Analyzer) and follow the directions [here](https://github.com/michaelsilver/Attribute-Analyzer#analyzing-the-attribute-graph) to import the necessary libraries and saved graph (will email that to you separately). Then execute the following list-comprehension:
```python
>>> for y in [(x, G.edge[x][u'']['infobox']) for x in G.predecessors(u'')]: print y
```

You can also confirm the findings by printing the mappings directly from your WikipediaBase (futuna has WikiBase installed):
```Python
>>> from wikipediabase.util import get_infobox, get_meta_infobox
>>> get_meta_infobox('Template:Infobox country').rendered_keys()
{'calling_code': 'Calling code', ... 
'DST_note': '',
...  # purposely abbreviated
'currency_code': 'Currency'}
```

**Comment by fakedrake** [comment]
Is it possible that they are actually not supposed to be mapped anywhere? Eg `motto_translated` has no attribute (see https://en.wikipedia.org/wiki/Spain). Should we return `None`?

**Comment by michaelsilver** [comment]
Sorry -- I must I have missed your response somehow. You note an interesting case, but I am not sure that this is the source of the problem since the following is returned for France's infobox:
```Python
>>> from wikipediabase.util import get_infobox, get_meta_infobox
>>> get_meta_infobox('Template:Infobox country').rendered_keys()
{'calling_code': 'Calling code',
'largest_city': u'Largest\xc2\xa0!!!!!largest_settlement_type!!!!!',
u'GDP_nominal_year': u'GDP\xc2\xa0(nominal)',
'demonym': 'Demonym',
'government_type': 'Government',
u'symbol_type': 'Flag',
'longm': '!!!!!admin_center_type!!!!!',
'cctld': 'Internet TLD',
u'common_name': u'Flag of\xc2\xa0!!!!!common_name!!!!!',
u'HDI': 'HDI (!!!!!HDI_year!!!!!)',
'longd': '!!!!!admin_center_type!!!!!',
'longEW': '!!!!!admin_center_type!!!!!',
u'HDI_ref': 'HDI (!!!!!HDI_year!!!!!)',
u'Gini': u'Gini\xc2\xa0(!!!!!Gini_year!!!!!)',
'official_languages': 'Official languages',
'ethnic_groups': u'Ethnic\xc2\xa0groups (!!!!!ethnic_groups_year!!!!!)',
u'Gini_ref': u'Gini\xc2\xa0(!!!!!Gini_year!!!!!)',
'languages': '!!!!!languages_type!!!!!',
'latd': '!!!!!admin_center_type!!!!!',
'DST_note': '',
u'population_census_year': u'\xc2\xa0-\xc2',
'footnote_a': 'a.',
'capital': '!!!!!admin_center_type!!!!!',
'latm': '!!!!!admin_center_type!!!!!',
'national_languages': u'Recognised national\xc2\xa0languages',
'footnote_b': 'b.',
'status': 'Status',
u'Gini_rank': u'Gini\xc2\xa0(!!!!!Gini_year!!!!!)',
'utc_offset': 'Time zone',
'nummembers': 'Membership',
'latNS': '!!!!!admin_center_type!!!!!',
'regional_languages': u'Recognised regional\xc2\xa0languages',
'membership': '!!!!!membership_type!!!!!',
'drives_on': 'Drives on the',
u'GDP_PPP_year': u'GDP\xc2\xa0(PPP)',
'antipodes': 'Antipodes',
'patron_saint': 'Patron saint',
'legislature': 'Legislature',
'date_format': 'Date format',
'currency': 'Currency',
u'population_estimate_year': u'\xc2\xa0-\xc2',
'loctext': 'Location',
'org_type': 'Type',
'time_zone': 'Time zone',
'religion': 'Religion',
u'HDI_rank': 'HDI (!!!!!HDI_year!!!!!)',
'footnote_h': 'h.',
'currency_code': 'Currency'}
```
Note that `englishmotto` is not there and rather `DST_note` is the only attribute with no rendered value. Any ideas why?

If an attribute really trully maps to nothing, then my inclination is to simply exlude it from the list. Any reason to keep it there? I think it would be just a pain for anyone using WikipediaBase to have to know to check for `None` or whatever we put in place of `''`. What do you think?

**Comment by alvaromorales** [comment]
To investigate: Why are attributes being mapped to the empty string? Can we improve the way we extract rendered attributes to avoid this?

If not, we should definitely **exclude** attributes that map to the empty string.

**Comment by cordeliaavery** [comment]
@alvaromorales  It looks like this is actually a much bigger problem with how the metainfoboxes are being parsed. As far as I can tell, the error occurs when an attribute has nested values (so if you look at France https://en.wikipedia.org/wiki/France, Population, Area, Government, etc. all have bullet points under them); these aren't stored in the same way, and the parser isn't handling it correctly. If you look at the list above, 'fr-metropole' maps to '\u2022', which is actually the bullet point character, whereas ideally we would have a nested structure resembling the following:

{'Population':  {'estimate' : (est. of total population) 
                        'fr_metropole' : (urban population)
                       }
}

Probably a third entry referencing population density, again nested, since it's in both km and miles; the same nested structure would apply to anything else with bullet points in the infobox.

**Comment by alvaromorales** [comment]
Ah, once again, Everything In Wikipedia Is Hard. I don't think we've seen this type of infobox before.

Modeling this infobox is challenging. The nested representation is a good idea. But I'm also thinking that many of these attributes aren't _useful_ from a question answering perspective. For instance, I can't think of anyone asking about `GDP-PPP-YEAR` (the year when the GDP estimate was calculated). Perhaps we can group the whole GDP section into one single `GDP` attribute.

Looking at the infobox markup, there's no explicit grouping of attributes. We could maybe logically group attributes by prefix (e.g. `GDP-NOMINAL` and `GDP-PPP-YEAR` by `GDP`). But this might hurt our ability to parse other infoboxes.

We should brainstorm this tomorrow with @sfelshin.

**Comment by alvaromorales** [comment]
`wikipedia-settlement` is also a good test case:

```python
get_meta_infobox('Template:Infobox settlement').attributes
```
