### ISSUE TITLE
Parse coordinates in infoboxes

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#265]
E.g., for https://en.wikipedia.org/wiki/Infinite_Loop_(street) which has coordinates in the infobox (class `wikipedia-street`) but not in the article body.  If this is intractably difficult due to complexity of markup, then we should punt.

**Comment by sfelshin** [comment]
Note that some articles have coordinates in the infobox _and_ in the article body, in which case there is no value in parsing coordinates in the infobox.  E.g., https://en.wikipedia.org/wiki/Leonard_P._Zakim_Bunker_Hill_Memorial_Bridge.

**Comment by chsamlee** [comment]
Wikipediabase never obtains coordinates from markup.
