### ISSUE TITLE
Tests are slow

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#27]
The test suite takes a long time to run.

On a fresh run (with no tests/data/pages.db), a test run took over 25 minutes in an InfoLab machine. Subsequent runs take around 160s, which still seems high for a unit test run.

Tests in tests.test_resolvers.TestResolvers are particularly slow.

I'm guessing that a lot of this has to do with the performance of the wikipedia-mirror. I'm investigating this, and trying to create a new mirror on CSAIL OpenStack. I'll start a beefy instance with enough RAM and cores, and work on MySQL performance tuning.

**Comment by fakedrake** [comment]
The performance bottlenecks are network io (how fast the mirror responds), and xml parsing (lxml that is). I used to use beautifulsoup and increased the testing speed nearly x10 by swapping it out for lxml. On issue #10 there is a hint on how I found out.

**Comment by alvaromorales** [comment]
Fixed by moving away from the wikipedia mirror.
