### ISSUE TITLE
Tests depend on the state of the Wikipedia mirror

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#28]
This issue was originally raised over email. Since Python-WikipediaBase is a layer on top of a Wikipedia installation (mirror or live), perhaps we should test its functionality independently of the underlying data. Instead of running could we save off rendered and unrendered articles into tests/data? Test behavior would thus be consistent across test runs, now or in six months.

Including the pages.db in tests/data is not an option, as gdbm is not portable across OSses (I verified this on a fresh install of WikipediaBase in Ubuntu 14.04).

@fakedrake: "One solution that I have started playing with is to distribute a json file with the relevant data and turn it into gdbm format before running the tests."

^ That's indeed possible, but perhaps not the simplest solution. It seems complicated to have to depend on gdbm for a test run. Why not just have .html and .txt files in tests/data, as needed, and have the fetcher fetch those? Perhaps using a mock?

**Comment by sfelshin** [comment]
"Instead of running could we save off rendered and unrendered articles into tests/data? Test behavior would thus be consistent across test runs, now or in six months."  Good idea, but we should _also_ test on live data, because WikiBase needs to react to changes in formatting (preferably by being so robust that it works on both old and new formatting without any changes to code or test cases) and in content (by updating test cases as needed).

**Comment by fakedrake** [comment]
The bottleneck of false negatives when running tests so far has been the actual information in wikipedia changing or being more precise (eg. see what it sais under "Born:" in Klaus Barbies page on [wikipedia](https://en.wikipedia.org/wiki/Klaus_Barbie) and on [ashmore's mirror](http://ashmore.csail.mit.edu:8080/mediawiki/Klaus_Barbie) )

I agree with Sue and I think the cleanest way to achieve both tests being predictable and is on solving issue #24 to have a separate category of tests that hit wikipedia.org or a mirror and see that nothing significant breaks.

**Comment by alvaromorales** [comment]
No longer using the wikipedia mirror. Tests hit live data.
