### ISSUE TITLE
Fix get-types on kiribati (works on navassa)

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#280]
```
$ telnet kiribati 8023
(get-types "RMS Titanic")
((:error wikipediabase-internal-error :message "ProgrammingError: relation \"types\" does not exist
LINE 1: ...CT \"t1\".\"id\", \"t1\".\"type_name\", \"t1\".\"count\" FROM \"types\" AS...
                                                             ^
"))
$ telnet navassa 8023
(get-types "RMS Titanic")
("British liner" "liner" "passenger liner")
```
I installed the latest WikipediaBase on kiribati as part of switching it to be the START production host (on Nov. 3, based on logged traffic).  What's the problem?

We'd now like to use `get-types` to provide data to our SRI collaborators, so this is pretty important.  We can use navassa in the short term.

@michaelsilver, I've assigned this to you with the expectation that you will decide whether to fix it yourself or reassign it to @amirfarhat.

**Comment by michaelsilver** [comment]
Looks like the most recent backend was never restored on kiribati. See the [instructions on the wiki](https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/WikipediaBase#Restoring_from_an_Existing_Backend).

I've started the process; should be done in an hour.

Just as a reminder there are two steps to install WikipediaBase:
  1. Install the python module (the "frontend") in the `wikipediabase` virtualenv via `python setup.py install`
  1. Restore the postgres backend via `restore-wikipediabase.sh`

**Comment by sfelshin** [comment]
Great; thanks! 😃   I hadn't realized that the existing backend was incompatible with the latest frontend.

**Comment by michaelsilver** [comment]
All set
