### ISSUE TITLE
Standardize Encodings

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#44]
The inconsistencies in encoding are getting quite difficult to deal with. See #41 for an example -- `get_meta_infobox('<TEMPLATE_NAME>').rendered_keys()` is returning a mix of what are Unicode types (with `u` prefix), and normal string types (without the `u` prefix). And further, the newest change, as I mentioned in #41, is that the `u` prefixed strings are what actually should be normal strings that are encoded in utf-8. For example, `'rate': u'Rate\xa0of\xa0fire'` should actually be `'rate': 'Rate\xa0of\xa0fire'` (note the lack of `u`) since '\xc2\xa0' is a utf-8 encoded string. When decoded, it yields a Unicode string u'\xa0':
```Python
>>> 'Rate\xc2\xa0of\xc2\xa0fire'.decode('utf8')
u'Rate\xa0of\xa0fire'
```
Which then yields a proper Unicode string, which can be dealt with accordingly with `unidecode`:
```Python
>>> unidecode(u'Rate\xa0of\xa0fire')
'Rate of fire'
```

I propose that all strings are of the normal Python string type, just encoded in utf-8 (meaning `'Rate\xc2\xa0of\xc2\xa0fire'` instead of `u'Rate\xc2\xa0of\xc2\xa0fire'`). This way, no information is lost, such as when it is transliterated using `unidecode`, and in the case that someone wants to transliterate it, it is possible to use unidecode without unexpected errors (see #41).

I would fix this myself, but I am having trouble wrapping my mind around why things are encoded and decoded in the code, such as in `fetcher.py`, `persistentkv.py`, and `renderer.py`, and I have no idea how one managed to get `u'Rate\xc2\xa0of\xc2\xa0fire'` instead of `'Rate\xc2\xa0of\xc2\xa0fire'`. Thoughts?

**Comment by alvaromorales** [comment]
+1 to agreeing on a standardized way to handle encodings.

My 2 cents: The more long-term approach would be to make all strings Unicode strings, and only use `unidecode` when outputting a string for START (enchantment?).

Omnibase will eventually support Unicode by upgrading to Guile 2.0. I assume that START will also support Unicode someday. When that day finally comes, we can just remove the call to `unidecode` and return a Unicode string.

--

Note that the printed 'u' prefix occurs when invoking the `__repr__` method instead of `__str__` (what `print` uses).

```python
>>> s = u"hello world"
>>> s.__repr__()
"u'hello world'"
>>> s.__str__()
'hello world'
>>> str(s)
'hello world' # equivalent
```

**Comment by michaelsilver** [comment]
> My 2 cents: The more long-term approach would be to make all strings Unicode strings, and only use unidecode when outputting a string for START (enchantment?).

Sounds good -- whatever is easier or more maintainable for the long term, as long as it is consistent!

> Omnibase will eventually support Unicode by upgrading to Guile 2.0. I assume that START will also support Unicode someday. When that day finally comes, we can just remove the call to unidecode and return a Unicode string.

Yup, it is nice to have an abstract `enchantment` layer to handle things like this; when the day finally comes, all we will have to do is just a minor change to the `enchantment` and we will be all good.

> Note that the printed 'u' prefix occurs when invoking the __repr__ method instead of __str__ (what print uses).

I am not sure that calling `__str__` is the solution. For just ascii strings, such as `"hello world"` you can call `__str__` no problem, but for strings with non-ascii text, you will get a `UnicodeEncodeError`, see the [Python Docs](https://docs.python.org/2/howto/unicode.html) for more details:

```Python
>>> s = u'Rate\xc2\xa0of\xc2\xa0fire'
>>> s.__str__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4-5: ordinal not in range(128)
```

But as I understand, the encoding in the three files I mentioned (`fetcher.py`, `persistentkv.py`, and `renderer.py`) have to do with utilities other than just the "front-end" proving to START -- maybe Chris can shed some light on why things are encoded/decoded where they are?

**Comment by sfelshin** [comment]
On Jul 5, 2015, at 7:43 PM, Alvaro Morales wrote:
> +1 to agreeing on a standardized way to handle encodings.
> 
> My 2 cents: The more long-term approach would be to make all strings Unicode strings, and only use unidecode when outputting a string for START (enchantment?).
> 
> Omnibase will eventually support Unicode by upgrading to Guile 2.0. I assume that START will also support Unicode someday. When that day finally comes, we can just remove the call to unidecode and return a Unicode string.

I agree!

-Sue

**Comment by alvaromorales** [comment]
I'm working on this via #31

**Comment by alvaromorales** [comment]
The big source of pain here was lxml, because it parses text inconsistently: sometimes as Unicode strings and sometimes as regular strings.
