### ISSUE TITLE
Caching proposal

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#46]
I've been getting familiar with how WikipediaBase does caching, and I have a few ideas on how to improve the current solution to make it production-ready. I would appreciate any feedback on this proposal.

### Summary

1. Move to Redis for caching source wikimarkup pages, HTML pages, rendered pages, and meta infoboxes
2. Remove Python object caching

### Redis

We need caching for two reasons: speed, and to reduce the number of requests to [wikipedia.org](https://en.wikipedia.org/wiki/Main_Page).

For those who don't know, [Redis](http://redis.io/) is an in-memory key value store. It is used by many websites for caching. It supports neat features like automatic key expiry, eviction policies, and data structures like sets or maps.

Since it runs in memory, it's very fast. If redis crashes, however, data is lost. We're using redis purely as a cache, not for storing any vital data. If we lose the cache, we simply bring redis back up and start with an empty cache (FWIW I'm not concerned by redis's stability since it's used by many companies in production).

I propose we replace gdbm with Redis due to 1) keys that automatically expire and 2) speed.

> Expires: Redis allows to set a time to live different for every key so that the key will be automatically removed from the server when it expires.

With auto-expiring keys we'll be able to mostly keep up with the latest version of Wikipedia.

Ideas for expiry policies:

* Source and rendered pages: 2-4 weeks
* Meta infoboxes: never, or something like 6 months

I would also like to introduce a hard dependency on Redis: WikipediaBase will need a Redis server running on localhost on port 6379 (default). Currently, some of the code assumes that there is a cache, some doesn't. I'd like to eliminate this added complexity. I believe that any intensive use of WikipediaBase will need caching anyway.

Our test server, Travis, supports starting a Redis container before the test suite run. We will be able to continue to use our continuous integration pipeline.

### Remove memoization

WikipediaBase tries to cache Python objects where possible (through `@memoize` and `_context_get` in `wikipediabase/util.py`). Here's a comment from the code:

```
    The context is actually a global cache used to keep track of the
    objects created and reuse them when possible.
    For example if I need an infobox for bill clinton I can get it by
    calling. _get_context('bill clinton', 'infoboxes' Infobox). which
    will create an Infobox instance for 'bill clinton' and cache
    it. If I later try to create an object in the same way, I will be
    reusing the old one.
    In place of symbol an object can be passed. In that case we return
    the object itself. This way we can have some flexibility with
    types and when calling get_<class>(<class instance>) have the
    right thing done.
```

I propose to remove `_context_get` because I don't think that the risks are worth it. The `_context_get` object cache will grow unboundedly -- there is no garbage collection. Objects are not invalidated with some sort of expiry policy (potential consistency issues).

The main bottleneck in WikipediaBase is not object creation, it's the network calls to wikipedia.org. I think we should trust that CPUs are fast and not worry about object caching.

Object caching brings difficult problems that I don't think WikipediaBase should attempt to solve. In a production environment, I would be extremely concerned with memory leaks, the lack of garbage collection, and eventually running out of memory.

**Comment by sfelshin** [comment]
I don't know the code base well enough to make specific comments, but I am very much in favor of NOT experiencing:

> memory leaks, the lack of garbage collection, and eventually running out of memory.

If we add Redis or anything else that uses a port, we should document port-assignments-in-use at
  https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/Ports

-Sue

**Comment by fakedrake** [comment]
First of all some "history" on what grounds the caching mechanism was built. Right now python wikipediabase uses lxml for parsing anything that comes from wikipedia.org. lxml is written is C and is generally as fast as it gets when it comes to parsing xml in python. However initially I used bautifulsoup which is extremely slow in comparison. That was the initial motivation of implementing caching. So while this specific problem was pretty much solved, I wouldn't underestimate the processing power required to process wikipedia articles.

Now the `CachingSiteFetcher`, which is the default implementation of the fetcher interface, indeed caches resources fetched from wikipedia.org. But notice that it does so in separate storage (see the `data` property of the class in `wikipediabase/fetcher.py`) from the rest of the system. The reason for this was the issue that @alvaromorales raises, in the sense that we would probably want different caching policies for computed resources and received resources.

Now about redis itself, I did consider redis for caching but I found it's deployment a bit complex. Besides, I figured that wikipediabase needs key-value storage and it shouldn't matter how it is implemented . So I abstracted the whole thing to  dict-like interface (see `wikipediabase/persistentkv.py`) and we can implement that with any solution we want. Then we can compare them (like we did with sqlite vs gdbm) and decide which one is best. 

To acomodate what @alvaromorales suggests about not caching internal resources, I expect that it would be trivial to implement the mentioned cache interface to miss every time and save nothing for resources not directly received from the network. I can try that tonight and see what the real performance hit is, if any, and what would the effect on memory footprint be.

**Comment by alvaromorales** [comment]
Thanks for the response! An experiment that measures the effect of disabling the Python object cache (on a realistic WikipediaBase workload) would be a great way of deciding where to go.

When I suggested Redis, performance was mostly a _secondary_ consideration. I'm more concerned about the lack of caching policies and the complexity that implementing those would bring. In the current implementation, when an HTML page is cached, it's cached forever. 

A caching solution is complex (we're still iterating on the system for Omnibase). I think WikipediaBase needs a fairly simple caching layer, and Redis auto-expiring keys would solve the problem. And it happens to be in-memory, so we get better performance "for free".

To better contextualize this proposal: I'm thinking of how to get WikipediaBase to production. In the START production host, Ruby-WikipediaBase has been running for over a year with no manual intervention. We don't worry about its memory footprint or have to clear its cache. We should be updating its MySQL backend, but it takes time and we haven't done it in a while (thus issue #31 that I'm working on).

Finally, I've had great experiences deploying Redis and don't believe it would increase our operational complexity.

**Comment by alvaromorales** [comment]
This proposal was implemented via the use of Redis and the LRUCache data structure for object caching.
