### ISSUE TITLE
Compatibility and classic modes

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#50]
In "compatibility mode", WikipediaBase returns an answer with a typecode, e.g. `((:html "George W. Bush"))`. The opposite is "classic mode". "Compatibility mode" is the expected behavior of WikipediaBase, as implemented by Ruby-WikipediaBase.

As the code is currently written, every query to `knowledgebase.py` runs in "compatibility mode" (`_get` never looks at the value of the `compat` param).

Why do we need a "classic" mode? Perhaps switching everything to effectively run in "compatibility mode" could help us remove unnecessary complexity.

At least, the naming of "compatibility" and "classic" modes should be changed to something more descriptive such as `typed_answer=True`.

**Comment by sfelshin** [comment]
On Aug 14, 2015, at 1:57 AM, Alvaro Morales wrote:
> In "compatibility mode", WikipediaBase returns an answer with a typecode, e.g. ((:html "George W. Bush")). The opposite is "classic mode". "Compatibility mode" is the expected behavior of WikipediaBase, as implemented by Ruby-WikipediaBase.
> 
> As the code is currently written, every query to knowledgebase.py runs in "compatibility mode" (_get never looks at the value of the compat param).
> 
> Why do we need a "classic" mode? Perhaps switching everything to effectively run in "compatibility mode" could help us remove unnecessary complexity.

Yes, it's time to kill off "classic mode".  We needed it for a while we were transitioning START to the new mode, but the transition has been complete for long enough that we're not going back to the old mode.  Off with its head!

-Sue
