### ISSUE TITLE
Enchantments return inconsistent results

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#68]
WikipediaBase should always return **a list of typed values**. Not all provided methods in KnowledgeBase return a list of values (for example, `get-attributes`).

Enchantments produce inconsistent results, sometimes wrapping the encoded object inside a list. For example, `EnchantedString` produces a Lisp-encoded **list of strings**, instead of a Lisp-encoded **string**. In addition, enchantments don't support nested lists.

Enchantments should take a Python object and produce a Lisp-like encoded string of the object. All enchantments should support typecodes. We need to add more unit tests.

**Comment by fakedrake** [comment]
while you are at it would you finally rename enchanted types to maybe Start{Type,String,List,...}? I would take this one but I am abroad until monday.

**Comment by alvaromorales** [comment]
Good call. I'll open a new issue to rename enchantments.

Fixed by #69

**Comment by sfelshin** [comment]
On Oct 1, 2015, at 11:00 AM, Chris Perivolaropoulos wrote:
> while you are at it would you finally rename enchanted types to maybe Start{Type,String,List,...}? I would take this one but I am abroad until monday.

I like your suggestion, Chris.  Although START is currently the only user of WikipediaBase, other programs might use it someday.  Alvaro said

On Oct 1, 2015, at 10:22 AM, Alvaro Morales wrote:
> Enchantments should take a Python object and produce a Lisp-like encoded string of the object. All enchantments should support typecodes. We need to add more unit tests.

It seems to me that "take a Python object and produce a Lisp-like encoded string" explains what enchantments do very nicely.  The tricky part is to reduce that to a short enough name.  ConvertToLisp?  OutputAsLisp?  ToLispSyntax?  Py2Lisp?  I'm not familiar with Python naming conventions, but I suggest something along these lines.

-Sue

**Comment by michaelsilver** [comment]
If we are discussing changing "enchant" to something else, why not just call it "lispify" or something like that?

**Comment by fakedrake** [comment]
yes that sounds good. So to summarize Lisp{Type, List, Bool... } (old
Enchant{... }) would be the various types that wrap python objects so they
can be shown as s-expressions that start can understand or parse
s-expressions, that probably come from start, into python objects. Then
lispify is the old enchant function that multiplexes the construction of
Lisp{... } objects from python objects.
