### ISSUE TITLE
Infobox attributes are deduplicated when rendering

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#70]
Wikipedia deduplicates synonymous attributes before rendering an infobox. If both `SUCCESSOR` and `SUCCEEDING` are in the infobox to render, only one gets rendered. This means we lose a lot of unrendered-rendered mappings.

Example:

```python
In [1]: from wikipediabase.metainfobox import MetaInfobox

In [2]: m = MetaInfobox('Template:Infobox president')

In [3]: len(m.attributes())
Out[3]: 160

In [4]: len(m.rendered_attributes())
Out[4]: 69
```

We only get rendered mappings for less than 50% of attributes. Instead of rendering all attributes in one infobox:

```
{{Infobox president
| succeeded = foo
| succeeding = foo
...
}}
```

A naive solution would be to render each attribute in its own infobox, e.g.:

```
{{Infobox president
| succeeded = foo
}}

{{Infobox president
| succeeding = foo
}}
```

However, this render query takes a long time.

We should find a way to separate attributes into the smallest number of disjoint sets, perhaps by looking at prefixes of attributes.

EDIT: note that synonymous attributes might render to different things. `SUCCESSOR` renders to 'Successor' and `SUCCEEDING` renders to 'Succeeding'.

**Comment by alvaromorales** [comment]
We should also ignore number suffixes when looking up rendered attributes. If we have a rendered mapping for `SUCCESSOR`, let's also use it for `SUCCESSOR1`, `SUCCESSOR2`, etc.

**Comment by sfelshin** [comment]
On Oct 1, 2015, at 10:48 AM, Alvaro Morales wrote:
> We should also ignore number suffixes when looking up rendered attributes. If we have a rendered mapping for SUCCESSOR, let's also use it for SUCCESSOR1, SUCCESSOR2, etc.
> 

Are there any cases where such attributes render differently?  Although source/rendered mappings are extremely useful for several of our systems, we don't need our precision and recall to be 100% perfect.  Would it be easy to test for alternate renderings, either comprehensively or with some sort of random spot-check, or would it be so time-consuming (either to implement or to run) that it's not worth it?

-Sue

**Comment by fakedrake** [comment]
i should note that the possible infobox types are very finite (about 70 in
total iirc). we could precompile those in a (regularly updated) database
since they are a performance bottleneck.

**Comment by alvaromorales** [comment]
I like the idea of precompiling meta infoboxes to the backend, I'll open an issue. There are actually around 3500 infobox templates.
