### ISSUE TITLE
Notice missing dependencies on Travis (pip caching)

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#75]
It bugs me that Travis is caching pip dependencies. I really think, especially for PRs that make changes to the `setup.py`, Travis aught to be installing from scratch (w/o caching) to mimic real use-case. Otherwise, it's possible that we delete a dep and don't notice that it actually is still needed until someone does a fresh install somewhere else. This is relevant during development because WikipediaBase is currently being used as a library in other projects (e.g. WikiMap), and it should be up to the WikipediaBase testing to make sure all dependencies are present at install. Otherwise, we might be merging code that breaks things (by a missing dependency) and not noticing it in Travis.

Does pip caching ever expire? Maybe there is some way to cache always, *except for when setup.py is modified*, in which case we do a fresh install and create a new cache? Thoughts?

**Comment by alvaromorales** [comment]
You raise good points! As far as I know, Travis does not support cache expiry. You can manually delete caches (Settings -> Caches on travis-ci.org), so we could encourage contributors to delete all caches when they update setup.py.

Two things:

1. I looked into it, and Travis caching is _not_ working for WikipediaBase. We have a custom install step and are missing a requirements.txt file. This is an open issue for Travis: https://github.com/travis-ci/travis-ci/issues/3239

2. I understand your concern of accidentally deleting a dependency, but I don't think that this would be a major problem in practice. Anyone attempting a fresh install would get an instant failure, would notice the missing dependency, and could easily fix the problem. If build times were really long and caching sped things up 10x, I think that caching dependencies would be the correct decision.

Build times for WikipediaBase are under 5 minutes, so I'm okay with disabling Travis caching altogether.
