### ISSUE TITLE
Errors parsing birth and death dates from the first sentence

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#77]
Richard Shakespeake was born in 1490 so he can't possibly still be alive, yet in Python WikiBase:

(get "wikibase-person" "Richard Shakespeare" (:code "BIRTH-DATE"))
((:YYYYMMDD 14900000))
(get "wikibase-person" "Richard Shakespeare" (:code "DEATH-DATE"))
((:ERROR ATTRIBUTE-VALUE-NOT-FOUND :REPLY "Currently alive"))

Compare Ruby WikiBase:

(get "wikipedia-person" "Richard Shakespeare" (:code "BIRTH-DATE"))
((:YYYYMMDD 14900000))
(get "wikipedia-person" "Richard Shakespeare" (:code "DEATH-DATE"))
((:YYYYMMDD 15610000))

Richard Shakespeare's first sentence says "Richard Shakespeare (1490–d. before 10 February 1561) was a husbandman of [snip]".  The death date is hard to parse, but python WikiBase should something reasonable, which could be:

  - return 1561 like ruby WikiBase
  - return a non-yyyymmdd value: ((:html "d. before 10 February 1561"))
  - deprecated option: return the empty set of values: ()
  - return the value both ways: ((:html "d. before 10 February 1561" :yyyymmdd 15610210))

**Comment by sfelshin** [comment]
I meant to say before: The presence of "–d. " after an apparent birth date should be a sufficient clue that the person is dead, even if the date(?) of death is too hard to interpret.

**Comment by alvaromorales** [comment]
@fakedrake where should the Richard Shakespeare bug be fixed? In WikipediaBase or overlay_parse?

The first sentence is:

> Richard Shakespeare (1490–d. before 10 February 1561) ...

This follows a common pattern: dates in parenthesis in the first sentence; birth date separated from death date by a hyphen. We should ignore periods in the parens.

**Comment by alvaromorales** [comment]
I found this example using Wikipedia's "Random Article".

```
(get "wikibase-person" "Adarnase II of Klarjeti" "BIRTH-DATE")
((:yyyymmdd 09450000))

(get "wikibase-person" "Adarnase II of Klarjeti" "DEATH-DATE")
((:error attribute-value-not-found :reply "Currently alive"))
```

when the first sentence reads:

> Prince Adarnase II (Georgian: ადარნასე) (died 945) was a Georgian royal prince of the Bagrationi dynasty of Tao-Klarjeti branch.

**Comment by sfelshin** [comment]
WikipediaBase 1.0.0 shows a nice improvement over the behavior reported in https://github.com/infolab-csail/WikipediaBase/issues/96:
```
$ telnet navassa 8023
(get-classes "Homer")
("wikibase-term" "wikibase-sections" "wikibase-person")
$ telnet navassa 8023
(get "wikibase-person" "Homer" (:code "DEATH-DATE"))
((:error attribute-value-not-found :message "Unknown"))
```
However, in WikipediaBase 1.1.0, progress is retrograde:
```
$ telnet kiribati 8023
(get-classes "Homer")
("wikibase-term" "wikibase-sections" "wikibase-person")
$ telnet kiribati 8023
(get "wikibase-person" "Homer" (:code "DEATH-DATE"))
((:error attribute-value-not-found :reply "Currently alive"))
```
Homer's first sentence is currently "Homer (Ancient Greek: Ὅμηρος [hómɛːros], Hómēros) is best known as the author of the Iliad and the Odyssey."  Since there is nothing even vaguely resembling either a birth date or a death date, we shouldn't claim he's alive.
