### ISSUE TITLE
"The (206)" is not a person so why is it a wikibase-person?

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#78]
The first sentence is "The (206) (styled “The [206]” on-screen) is a local sketch comedy television show in [snip]".  This should not lead us to think it's a person.

(get-classes "The (206)")
("wikibase-term" "wikibase-sections" "wikipedia-television" "wikibase-person")

(get "wikibase-person" "The (206)" (:code "BIRTH-DATE"))
((:yyyymmdd 02060000))

(get "wikibase-person" "The (206)" (:code "DEATH-DATE"))
((:error attribute-value-not-found :reply "Currently alive"))

**Comment by alvaromorales** [comment]
This was fixed at some point, "The (206)" is no longer a wikibase-person.
