### ISSUE TITLE
Check length of first paragraph for the SHORT-ARTICLE attribute

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#81]
The expected behavior of the SHORT-ARTICLE attribute for wikibase-term is to return:

> The first paragraph of the article, or if the first paragraph is shorter than 350 characters, then returns the first paragraphs such that the sum of the rendered characters is at least 350.

We're currently returning the first paragraph without checking its length.

**Comment by alvaromorales** [comment]
The short-article attribute is provided by TermResolver: https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/resolvers/term.py#L105

**Comment by sfelshin** [comment]
On Oct 20, 2015, at 3:34 PM, Alvaro Morales <notifications@github.com> wrote:
> The expected behavior of the SHORT-ARTICLE attribute for wikibase-term is to return:
> 
> The first paragraph of the article, or if the first paragraph is shorter than 350 characters, then returns the first paragraphs such that the sum of the rendered characters is at least 350.

The correct behavior is more complicated: If the SHORT-ARTICLE value is too short, it should get extended with extra text, it should get truncated, and furthermore, the text shouldn't get truncated in the middle of a word, and the return value should be legal HTML (no unclosed elements).  Do we have test cases for all that?

IIRC, the SHORT-ARTICLE script is also supposed to truncate the first paragraph if it's really long (and also not in the middle of a word, and as legal HTML) -- check the obsolete ruby implementation for the maximum length for a first paragraph.

**Comment by alvaromorales** [comment]
Interesting. That method specification is from the wiki page. I looked at the Ruby-WikipediaBase code, and there's no truncation step. If the first paragraph is shorter than 350 characters, it keeps adding paragraphs until the total length is > 350 characters. This behavior is what Sherry's PR implemented.

Of course, we can open a new PR and change this. However, I'm not sure I see the point of truncating text in the middle of a sentence. I think it would reduce answer legibility. Are there any sample questions where START truncates snippets?

We don't have a test case that checks whether the return value is legal HTML. @sherryy can you add this test in a new PR?

**Comment by sfelshin** [comment]
On Jan 6, 2016, at 6:19 PM, Alvaro Morales <notifications@github.com> wrote:
> Interesting. That method specification is from the wiki page. I looked at the Ruby-WikipediaBase code, and there's no truncation step. If the first paragraph is shorter than 350 characters, it keeps adding paragraphs until the total length is > 350 characters. This behavior is what Sherry's PR implemented.
> 
> Of course, we can open a new PR and change this. However, I'm not sure I see the point of truncating text in the middle of a sentence. I think it would reduce answer legibility. Are there any sample questions where START truncates snippets?

Well, maybe I'm misremembering about truncation.  For short SHORT-ARTICLEs, is the behavior to lengthen by _paragraphs_ rather than words?  If so, maybe we did that so that we could assume the result would be legal paragraph-level HTML.  (But note that the HTML result is allowed to be illegal if the Wikipedia source is illegal.)

**Comment by alvaromorales** [comment]
Yes, for SHORT-ARTICLE, the behavior is to lengthen by _paragraphs_. WikipediaBase used to return:

> <p><b>Astaroth</b> (also <b>Ashtaroth</b>, <b>Astarot</b> and <b>Asteroth</b>), in <a href="https://en.wikipedia.org/wiki/Demonology" title="Demonology">demonology</a>, is the Great Duke of <a href="https://en.wikipedia.org/wiki/Hell" title="Hell">Hell</a>, in the first hierarchy, between Belzebub and Lucifer, he is part of the evil trinity. He is a male figure named after the <a href="https://en.wikipedia.org/wiki/Canaan" title="Canaan">Canaanite</a> goddess <a href="https://en.wikipedia.org/wiki/Ashtoreth" title="Ashtoreth" class="mw-redirect">Ashtoreth</a>.</p>

Now, we return an answer longer than 350 characters:

> <p><b>Astaroth</b> (also <b>Ashtaroth</b>, <b>Astarot</b> and <b>Asteroth</b>), in <a href="https://en.wikipedia.org/wiki/Demonology" title="Demonology">demonology</a>, is the Great Duke of <a href="https://en.wikipedia.org/wiki/Hell" title="Hell">Hell</a>, in the first hierarchy, between Belzebub and Lucifer, he is part of the evil trinity. He is a male figure named after the <a href="https://en.wikipedia.org/wiki/Canaan" title="Canaan">Canaanite</a> goddess <a href="https://en.wikipedia.org/wiki/Ashtoreth" title="Ashtoreth" class="mw-redirect">Ashtoreth</a>.</p>
<p>The name <i>Astaroth</i> was ultimately derived from that of <a href="https://en.wikipedia.org/wiki/2nd_millennium_BC" title="2nd millennium BC">2nd millennium BC</a> <a href="https://en.wikipedia.org/wiki/Phoenicia" title="Phoenicia">Phoenician</a> goddess <a href="https://en.wikipedia.org/wiki/Astarte" title="Astarte">Astarte</a>,<sup id="cite_ref-1" class="reference"><a href="https://en.wikipedia.org/wiki/Astaroth#cite_note-1"><span></span>1<span></span></a></sup> an equivalent of the Babylonian <a href="https://en.wikipedia.org/wiki/Ishtar" title="Ishtar">Ishtar</a>, and the earlier Sumerian <a href="https://en.wikipedia.org/wiki/Inanna" title="Inanna">Inanna</a>. She is mentioned in the <a href="https://en.wikipedia.org/wiki/Hebrew_Bible" title="Hebrew Bible">Hebrew Bible</a> in the forms <i>Ashtoreth</i> (singular) and <i>Ashtaroth</i> (plural, in reference to multiple statues of her). This latter form was directly transliterated in the early Greek and Latin versions of the Bible, where it was less apparent that it had been a plural feminine in Hebrew.</p>

**Comment by sfelshin** [comment]
In that case, I withdraw the comment.
