### ISSUE TITLE
(get "wikipedia-sea" "Black Sea" (:code "LENGTH" :rendered "Max. length")) --> malformed error

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#83]
WikiBase is mishandling a `get` call where the attribute is specified with both `:code` and `:rendered` attribute names, and it's also mishandling the error it returns.  `get` must always return a list of values, each of which is a list.  E.g., `((:error ...))` but not `(:error ...)`. Note this bogus value:

> $ telnet nauru 8023
> (get "wikipedia-sea" "Black Sea" (:CODE "LENGTH" :RENDERED "Max. length"))
> (:error TypeError :message "lispify() got multiple values for keyword argument 'typecode'")

Regarding the `:code ... :rendered ...` issue, compare:

> $ telnet nauru 8023
> (get "wikipedia-sea" "Black Sea" (:code "LENGTH"))
> ((:html "1,175 km (730 mi)"))
> $ telnet nauru 8023
> (get "wikipedia-sea" "Black Sea" (:rendered "Max. length"))
> ((:error attribute-value-not-found :reply "Unknown"))

It's a bug that `get` fails with a rendered attribute name, but at least it fails with a well-formed error message.

**Comment by sfelshin** [comment]
Another case of a malformed error value.  This:

> $ telnet nauru 8023
> (get-classes "IS (manga)")
> (:error AssertionError :message "")

should return `((:error AssertionError :message ""))`.  Note the extra parens.

**Comment by alvaromorales** [comment]
The bug with malformed errors is now fixed. This issue will be closed when #79 is merged.

I'll open a new issue to handle the mishandling of a get call where the attribute is specified with both :code and :rendered attribute names.

**Comment by michaelsilver** [comment]
I will review #79 when I get home. Sorry for the delay.

**Comment by alvaromorales** [comment]
No rush, @michaelsilver!

I restarted the Wikibase server on nauru for @sfelshin to continue testing. This issue is no longer blocking her.
