### ISSUE TITLE
"km2" misindicates square kilometers

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#88]
Here's what WikiBase currently returns:

    $ telnet nauru 8023
    (get "wikipedia-sea" "Black Sea" (:code "AREA"))
    ((:html "436,402&#160;km2 (168,500&#160;sq&#160;mi)"))

Here's the wikimarkup:

    | area               = {{convert|436402|km2|sqmi|-2|abbr=on}}

Here's the HTML source:

    <td>436,402&#160;km<sup>2</sup> (168,500&#160;sq&#160;mi)</td>

Shouldn't WikiBase return this?:

    $ telnet nauru 8023
    (get "wikipedia-sea" "Black Sea" (:code "AREA"))
    ((:html "436,402&#160;km<sup>2</sup> (168,500&#160;sq&#160;mi)"))

(Or alternatively `...436,402 sq km` or `...436,402 square kilometers`, but that seems like unhelpful complication of code.)

**Comment by sfelshin** [comment]
P.S. Ditto for `"VOLUME"` --> `km3`.

**Comment by sfelshin** [comment]
On investigation, @alvaromorales and I find that we strip HTML before returning attribute values, causing the `<sup>` tags to disappear. We can't simply eliminate that code and retain all HTML, because then we would sometimes get illegal HTML in results.  Again, consider

    (get "wikipedia-sea" "Black Sea" (:code "AREA"))

If we don't strip HTML, we get

    <td>436,402&#160;km<sup>2</sup> (168,500&#160;sq&#160;mi)</td>

It's illegal for a `td` element to appear outside of a `tr` element (which is itself illegal outside of a `table` element).  (Note that START expects all values returned by `get` to be legal if inserted into an HTML document at paragraph level.)  Should we wrap `table` and `tr` elements?  Probably not; that could lead to weird display, especially if someone has defaulted tables to be displayed with borders.  Should we strip a `td` element if it wraps the value?  Probably.  But what if the value contains multiple `td` elements, e.g.,

    <td>one</td><td>two</td>

or any other HTML that isn't legal at paragraph level?  We need to think about this more.

**Comment by fakedrake** [comment]
The reasoning behind [the code there](https://github.com/infolab-csail/WikipediaBase/blob/backend/wikipediabase/infobox.py#L737L750) is that we remove all markup to make sure no weird stuff like this sneaks into the answer and whitelist only tags that we know are good, specifically `li`, `ul` and `br`. So now all line breaks and lists are allowed in but nothing else. Of course there is a potential bug in the case where we have a malformed list in a field but that is different can of worms.

One way to deal with this is to whitelist `sup` and `sub` , and keep whitelisting tags. The other is to throw potential invalid `td` and `a` elements and keep everything else trusting that there are no other weird stuff wikipedia does that we haven't thought of.

If we go with the whitelist approach, other text formatting tags that probably should be whitelisted are `<b> <em> <i> <small> <strong> <sub> <sup> <ins> <del> <mark>`

**Comment by sfelshin** [comment]
"Weird stuff"?  Why would we want to eliminate _any_ HTML?  I see that there are some tricky problems.  As noted earlier, we need to figure out how to make the result be legal paragraph-level HTML.  If the HTML contains relative URLs (e.g., in footnotes), we need to fully qualify the URLs.  (I assume Python has a library for that, but if not, we have a Guile function we could translate.)

For now, I'm content with whitelisting <sup> and a few more tags, but how about if we consider it an enhancement to try to retain all tags?

**Comment by alvaromorales** [comment]
@cordeliaavery see #105 for a full way to do this (including unit tests). The patch just needs to be de-conflicted with the HTML parsing code you refactored.

**Comment by alvaromorales** [comment]
Closed via #149
