### ISSUE TITLE
no attribute-value-not-found error for wikibase-term IMAGE-DATA

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#89]
Currently:

    $ telnet nauru 8023
    (get "wikibase-term" "The Tiger (1978 film)" (:CODE "IMAGE-DATA"))
    ((:error attribute-value-not-found :reply "Unknown"))

Every wikibase-term has an IMAGE-DATA attribute with a valid value.  When an article doesn't have any images (as with `The Tiger (1978 film)`), the correct return value is the empty list, `()`. IMAGE-DATA should not throw `attribute-value-not-found`.

**Comment by sfelshin** [comment]
On mature consideration, if there are no images, the correct return value is the empty list, `()`.

**Comment by sfelshin** [comment]
Another bug with `IMAGE-DATA`: empty filename.  If there are no images, the correct value is the empty list; the article has a couple of pictorial icons, which should either be completed ignored or returned as valid images.

    $ telnet nauru 8023
    (get "wikibase-term" "The Tiger (newspaper)" (:CODE "IMAGE-DATA"))
    ((0 ""))

**Comment by sfelshin** [comment]
Another bug: invalid filename:

    $ telnet nauru 8023
    (get "wikibase-term" "Tiger (cryptography)" (:CODE "IMAGE-DATA"))
    ((0 "" "
    "))

The wiki markup starts

    {{Infobox cryptographic hash function
    | name           = Tiger
    | image          = 
    | caption        = 
    
    | designers      = [[Ross J. Anderson|Ross Anderson]] and [[Eli Biham]]

and this seems to have confused the image parsing code.

**Comment by alvaromorales** [comment]
Also see #110
