### ISSUE TITLE
Illegal values for rendered attributes

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#90]
Illegal tokens used by MetaInfobox (e.g. `!!!!!term!!!!!`) are being included in the output.

```python
>>> wikipediabase('(get-attributes "wikipedia-french-commune" "Bouix")')
>>> '((:code "MAYOR" :rendered "* Mayor (!!!!!term!!!!!)") (:code "POPULATION" :rendered "* !!!!!total type!!!!!"))'
```

**Comment by alvaromorales** [comment]
In `wikipediabase/infobox.py`, look at `MetaInfoboxBuilder:rendered_attributes`

https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/infobox.py#L618

An attribute should only be added to the `attrs` dict if it's rendered attribute does not contain "!!!!!".

**Comment by cordeliaavery** [comment]
@alvaromorales to clarify, did you want to get rid of the extra "!!!!!", or just not include the entire attribute?

**Comment by alvaromorales** [comment]
I think we need to not include the attribute altogether. See https://github.com/infolab-csail/WikipediaBase/issues/23 for an explanation of where the "!!!!!" comes from.
