### ISSUE TITLE
Homer's lack of birth and death dates should result in attribute-value-not-found, not AssertionError

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#96]
(get "wikibase-person" "Homer" (:CODE "BIRTH-DATE"))
    ((:error AssertionError :message ""))

I think the correct output would be

    ((:error attribute-value-not-found ...))

(As far as I know, we currently have no specification for the elliptical material, and START will be okay the value is simply `((:error attribute-value-not-found))`.)

**Comment by alvaromorales** [comment]
This is a very interesting bug. An assertion that checks that the number of infoboxes in the markup is <= number of infoboxes in the HTML is failing.

On November 14 2015, a Wikipedia editor _removed_ Homer's infobox (!). You can see the back and forth, and their reasoning, [here] (https://en.wikipedia.org/w/index.php?title=Homer&action=history) and [here](https://en.wikipedia.org/wiki/Talk:Homer#Infobox.2FBiography).

The backend was built using the Oct 2 dump, so there's an inconsistency between the source and rendered versions.

I think we should leave this issue open for a while and see what happens to the Homer article, before deciding whether to change the code.

**Comment by sfelshin** [comment]
Well! I feel quite educated about Homer. Or not-Homer, or whatever.

I chose Homer as a test case because I wanted someone who Wikipedia thinks is a person but who doesn't have known birth or death dates in the first paragraph.  I'll switch to a different test case, but let's wait and see anyway about Homer, because if they eventually decide to keep the Homer article (as opposed to changing it to an article about the Homer controversy, or Homeric poetry), then we should make sure that WikipediaBase detects that Homer is a wikibase-person and doesn't barf on BIRTH-DATE and DEATH-DATE attributes.

**Comment by sherryy** [comment]
The page of Susan Pamerleau doesn't have an infobox, but when I was trying to retrieve the image-data, the number of info boxes obtained from get_infoboxes(article) is 1.
