### ISSUE TITLE
markup appears in :html value (F-16 unit cost)

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#97]
(get "wikipedia-aircraft-type" "General Dynamics F-16 Fighting Falcon" (:CODE "UNIT-COST"))
    ((:html "F-16A/B: {{US$|link=yes|14.6 million}} (1998 dollars)<ref name=AF_fact_sh/> <br>F-16C/D: {{US$|18.8 million}} (1998 dollars)<ref name=AF_fact_sh/>"))

**Comment by alvaromorales** [comment]
Yikes! This is caused by two issues: #84 and #98

**Comment by chsamlee** [comment]
A problem with this specific query is that the rendered attribute "unit cost" is incorrectly placed under "wikipedia-aircraft-begin" even though the corresponding markup attribute "unit-cost" is under "wikipedia-aircraft-type". This also needs to be fixed before the query can return the correct answer.
